services:
  - type: web
    name: yandex-reviews-app
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
